### ISSUE TITLE
Unable to cancel timer

### ISSUE THREAD

**Issue by Londonmark99** [FlyingDiver/Indigo-Occupatum#16]
Hi,

I'm trying to cancel a timer.
<img width="837" alt="Screenshot 2022-10-06 at 09 20 38" src="https://user-images.githubusercontent.com/41419854/194260495-dcc52048-27f5-4aeb-baac-414da6460825.png">

But when the action is executed, I get a message saying that no timer is found. Debug log here:

```
Occupatum Debug                 Watched Device updated: Mark's study sensor is now False
   Occupatum Debug                 Mark's study occupied?: checkSensors, onSensorsOnOff = on, onAnyAll = any, sensors: [559505105]
   Occupatum Debug                 Mark's study occupied?: checkSensors, occupied = False, previous = True, delay = 600.0
   Occupatum Debug                 Mark's study occupied?: checkSensors, adding delay timer with value = 600.0, occupied = False
   Occupatum Debug                 Watched Device updated: Mark's study sensor is now True
   Occupatum Debug                 Mark's study occupied?: checkSensors, onSensorsOnOff = on, onAnyAll = any, sensors: [559505105]
   Occupatum Debug                 Mark's study occupied?: checkSensors, occupied = True, previous = True, delay = 0.0
   Occupatum Debug                 Mark's study occupied?: checkSensors, adding delay timer with value = 0.0, occupied = True
   Occupatum Debug                 Mark's study occupied?: delayTimerComplete, occupied = True
   Z-Wave                          received "Mark's Study Light" scene 11
   Z-Wave                          received "Mark's Study Light" status update is off
   Trigger                         Mark's study lamp off when main light off
   Trigger                         Mark's study lamp off when main light off
   Trigger                         Mark's study lamp off when main light off
   Trigger                         Mark's study switched off manually
   Occupatum Debug                 cancelTimer, zoneDevice=630586532, pluginAction=configured : True
delayAmount : 900
description : cancel timer for zone
deviceId : 630586532
pluginId : com.flyingdiver.indigoplugin.occupatum
pluginTypeId : cancelTimer
props : com.flyingdiver.indigoplugin.occupatum : (dict)
     state : off (string)
replaceExisting : True
textToSpeak : 
   Occupatum Warning               Mark's study occupied?: cancelTimer, no timer found
```

**Comment by FlyingDiver** [comment]
Sorry I ner responded to this.  You filed it when we were out of the country, and then we were dealing with Hurricane Ian when we got back.

Looking at the log, I see this: 
`   Occupatum Debug                 Mark's study occupied?: delayTimerComplete, occupied = True`

The cancel action is after this, so I don't think the timer was still running.

**Comment by FlyingDiver** [comment]
Also, looks like you have delay timers on both the false and true states.  You can only have one active timer, so the "true" timer with delay 0 replaced the "false" timer with delay 600.

**Comment by michael-murdza** [comment]
I have a similar issue -
In my case, think it's because of the delayed off - _on some of my motion sensors_. 
I have multiple brands/models - some of them send an instant off while others have a delay of about 30 seconds (from last motion sensed). 
The instant off models immediately send an "off" status, triggering the occupatum countdown - and "Cancel TImer" works.
On the sensors with delayed off, occupatum is still in an "on" state - so there's no countdown yet - causing the error.

Considering there is an option to turn the zone off already in the Cancel Timer > Edit Action > Change Zone State dialog, I think it would make sense to cancel the timer, if active, and if it's "on" - then respect the selection in the "change zone state" option dialog (and turn it off).

**Comment by FlyingDiver** [comment]
I'm really not understanding the scenario you are describing.   First, keep in mind that there can only be one timer active on a zone at any time.  So if you have time delays on both zone on and zone off, if the zone changes state again before the first timer has completed, then it will never complete - it'll get overwritten by the other state timer.

The OP's issue was caused by having both on and off timers, so the on timer didn't exist when he tried to cancel it.  It was overridden by the off timer, which had already completed.

**Comment by michael-murdza** [comment]
Ok - then not exactly the same problem as I ONLY have the timer on the Occupatum zone - and NOT on the triggered actions like OP. 
My scenario is slightly different - i thought a quick sketch would be easier to articulate - let me know if this isn't as clear as I think it is :) 

**Here is the happy path - which works fine..**
![Happy path](https://user-images.githubusercontent.com/99281135/217298084-23178ab1-e3cc-49a9-88a7-348033de8679.png)


**Here is the use case I'm having trouble-with:**
![Override path](https://user-images.githubusercontent.com/99281135/217298121-908c47b2-1906-49a4-aa3d-f300f12cc389.png)

**Comment by FlyingDiver** [comment]
I would pro-actively cancel the timer (and set the zone to off) when the Light is forced off via switch.

**Comment by FlyingDiver** [comment]
Another thought - do these particular motion sensors always delay exactly 30 seconds before turning off, or is it 30 seconds after last motion detected?  My Lutron sensors won't send the off as long as they're still detecting motion.

**Comment by michael-murdza** [comment]
> I would pro-actively cancel the timer (and set the zone to off) when the Light is forced off via switch.
 - that's exactly what I'm trying to do, but because the timer hasn't yet begun, i get an error..
Ideally, the cancel timer action should cancel the timer if running, or turn the zone to "OFF" if it is in an "ON" state..


> Another thought - do these particular motion sensors always delay exactly 30 seconds before turning off, or is it 30 seconds after last motion detected? My Lutron sensors won't send the off as long as they're still detecting motion.
- about 30-40 seconds After the last motion occurs..  right now, i'm working around by delaying the "cancel timer" action by 45 seconds AFTER the switch triggers it...  which breaks if you walk back into the room within 45 seconds (lights don't come on b/c occupatum thinks they are on).
- I have some sensors that send an immediate off (which generates a TON of Insteon traffic (on-off-on-off-on-off as you walk thru a zone - which delays the lights turning on by about 1-2 seconds because of congestion..)
-- however, my use case works really well on these - I have a brief 5 second delay, so you can flip the switch, walk out and walk back in and the lights come on..

thanks

**Comment by FlyingDiver** [comment]
This is still on my radar, but I've been too busy to look at it and most of March will be the same.

But I'm looking at your "Override path", and wondering where exactly the problem is.  Is it that you can't force the zone off when the light is manually operated, but instead have to wait for the motion sensor to turn off?

Seems like there's a way to fool this.  Like instead of using the actual motion sensor as an input to the zone, use a virtual device that you turn on and off with triggers based on both the motion sensor AND the wall switch.  ON with motion, OFF with motion OR wall switch.  You might need to use Masquerade to make the virtual device look like a sensor, I don't recall.

**Comment by michael-murdza** [comment]
Hi, thanks for still thinking about this! Yes - the problem is, I cannot force the zone off when the wall switch is pressed if the timer has started yet (because it's waiting for an off command from the motion sensor). I think I started going down the path of using a surrogate like you mentioned - for a different reason - but I'll give that a try. 

Another thing I tried was to use the universal controls to send an "off" command to the occupatum instance (vs. the "cancel timer" action) - but it does't appear to support an "off" command.

thanks - I'll look at the virtual solution and see if that helps.  But tbh, what I love about occupatum was the fact that it was self contained..  Ive been trying to get occupancy right for about 10 years (with indigo) - and have implemented many solutions that involve multiple "state" variables and subsequent recurring actions to maintain them  - the next you know every motion sensor has half a dozen dependent artifacts that need to be created..  I originally posted a question around objects and properties to try and simplify it - at that point I learned that I would need to create a plugin for it - which you then graciously jumped on and delivered..  
thanks again!

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Occupatum/releases/tag/2022.1.6

I added an action to force a zone off.

**Comment by michael-murdza** [comment]
awesome, I'll check it out this weekend and let you know.. 

thanks!

**Comment by FlyingDiver** [comment]
Does that change work for you?

**Comment by michael-murdza** [comment]
Hey - thanks for adding this and sorry for my delay in reviewing it...  

I added the new action when the Insteon wall switch is activated, but unless i'm doing something wrong - it doesn't seem to work :(    The timer continues to decrement - I was expecting the state to go to "off"

**screens:**
<img width="615" alt="force zone 1" src="https://github.com/FlyingDiver/Indigo-Occupatum/assets/99281135/e2e8f5af-d709-457d-b2a9-cd0ca0bd3d1a">
<img width="615" alt="force zone 2" src="https://github.com/FlyingDiver/Indigo-Occupatum/assets/99281135/5dc32cee-a1a5-4546-ae34-43b5009fb11a">


**debug:**
```
   Occupatum Debug                 Mancave Occupatum OFF: Testing Event Trigger
   Occupatum Debug                 Mancave Occupatum OFF: Match on Zone Mancave Motion Sensor Occupatum v2
   Occupatum Debug                 MIchael Office Motion Trigger - Occupatum OFF: Testing Event Trigger
   Occupatum Debug                 MIchael Office Motion Trigger - Occupatum ON: Testing Event Trigger
   Trigger                         Mancave Occupatum ON
   Sent INSTEON                    "Mancave Lights" on to 100
   
// here is where I tap the switch and use the new "Force Zone Off" >>>
Received INSTEON                "Mancave Lights" off
   Trigger                         Manual Off - Cancel Mancave Timer
   Occupatum Debug                 forceZoneOff, zoneDevice=1894671987
   Occupatum Debug                 validate_force_zone_off_action, errors=Item : (dict)
   Received INSTEON                "EZIO8SA - for Motion Sensors" inputs status changed: 1, 1, 1, 0, 0, 0, 0
   Occupatum Debug                 Watched Device updated: Mancave Ceiling Motion - Masq via EZIO8 is now False
   Occupatum Debug                 Mancave Motion Sensor Occupatum v2: checkSensors, onSensorsOnOff = on, onAnyAll = any, sensors: [1623301763]
   Occupatum Debug                 Mancave Motion Sensor Occupatum v2: checkSensors, occupied = False, previous = False, delay = 300.0
   Occupatum Debug                 Mancave Motion Sensor Occupatum v2: checkSensors, adding delay timer with value = 300.0, occupied = False

```

**Comment by michael-murdza** [comment]
also - i'm testing [these motion sensors](https://www.adafruit.com/product/189) as a replacement for the ones i'm currently using that don't offer a delay and thereby flood the network with on/off insteon traffic..  I currently have a mix of different security system sensors that either offer no delay or others that use a fixed delay..  These, so far, are very affordable (even cheaper on amazon) - and I designed/printed a sleek, modern housing for them..  I like them a lot so far - the fact that I can use a consistent/configurable delay is great.

![motion sensor](https://github.com/FlyingDiver/Indigo-Occupatum/assets/99281135/760a1def-7237-497e-83ce-3b03a47788cf)

**Comment by FlyingDiver** [comment]
You need to cancel the timer AND force the zone off.

If that doesn't work, I'll need debug logs of the sequence of events.

**Comment by FlyingDiver** [comment]
Does the force off PLUS a cancel timer do what you need?
